langchain4j:
  community:
    dashscope:
      chat-model: # 阻塞式的调用【等大模型将所有信息全部打包生成完毕统一返回】
        api-key: sk-8de8b8e9f68048b18bf58c582b0cd2cc
        model-name: deepseek-v4-pro

      streaming-chat-model: # 注入流式调用的对象
        # 什么是流式调用：在调用第三方接口的时候，只要第三方接口有一定的答案，则会将数据进行返回，而不是等整个答案生成完毕再统一返回【打字机的效果】
        api-key: sk-8de8b8e9f68048b18bf58c582b0cd2cc
        model-name: deepseek-v4-pro